name: Tests and linting
 
on: [push, pull_request]

jobs:
  tox:
    runs-on: ubuntu-latest
    env:
      TOX_PARALLEL_NO_SPINNER: 1 # Removes logging spam
    steps:
      - name: Setup Pythons
        uses: actions/checkout@v2 # Required
      - uses: actions/setup-python@v2
        with:
          python-version: '3.7'
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install tox and run tests
        run: |
          pip install tox
          tox --parallel

  isort:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Pythons
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          pip install isort==5.9.3
          isort --settings-file pyproject.toml --check-only .
